FROM golang:1.21.1

WORKDIR /Europa

COPY go.mod go.sum ./

RUN go mod download

COPY Europa/names.txt . /Europa
COPY Europa/main.go ./

RUN go get github.com/Francisca-Gonzalez/Lab2_distribuidos

RUN go build -o Europa_bin .

ENTRYPOINT [ "/Europa/Europa_bin" ]