FROM golang:1.21.1

WORKDIR /datanode-1

COPY go.mod go.sum ./

RUN go mod download

COPY datanode-1/main.go ./

RUN go get github.com/Francisca-Gonzalez/Lab2_distribuidos

RUN go build -o datanode-1_bin .

ENTRYPOINT [ "/datanode-1/datanode-1_bin" ]