FROM golang:1.21.1

WORKDIR /Australia

COPY go.mod go.sum ./

RUN go mod download

COPY Australia/names.txt . /Australia
COPY Australia/main.go ./

RUN go get github.com/Francisca-Gonzalez/Lab2_distribuidos

RUN go build -o Australia_bin .

ENTRYPOINT [ "/Australia/Australia_bin" ]