FROM golang:1.21.1

WORKDIR /Asia

COPY go.mod go.sum ./

RUN go mod download

COPY Asia/names.txt ./Asia
COPY Asia/main.go ./

RUN go get github.com/Francisca-Gonzalez/Lab2_distribuidos

RUN go build -o Asia_bin .

ENTRYPOINT [ "/Asia/Asia_bin" ]