FROM golang:1.13

WORKDIR /I1

COPY go.mod go.sum ./

RUN go mod download

COPY I1/main.go ./

RUN go get github.com/NicoPUSM/PruebaLab1/Prueba-Lab1/proto

RUN go build -o I1_bin .

ENTRYPOINT [ "./I1_bin" ]