FROM golang:1.13

WORKDIR /broker
COPY go.mod go.sum ./

RUN go mod download

COPY broker/main.go ./

RUN go get github.com/NicoPUSM/PruebaLab1/Prueba-Lab1/proto

RUN go build -o Broker_bin .

ENTRYPOINT [ "./Broker_bin" ]