FROM golang:1.13

WORKDIR /F1

COPY go.mod go.sum ./

RUN go mod download

COPY F1/main.go ./

RUN go get github.com/NicoPUSM/PruebaLab1/Prueba-Lab1/proto

RUN go build -o F1_bin .

ENTRYPOINT [ "./F1_bin" ]