FROM golang:1.21.1

WORKDIR /datanode-2

COPY go.mod go.sum ./

RUN go mod download

COPY datanode-2/main.go ./

RUN go get github.com/Francisca-Gonzalez/Lab2_distribuidos

RUN go build -o datanode-2_bin .

ENTRYPOINT [ "/datanode-2/datanode-2_bin" ]