FROM golang:1.21.1

WORKDIR /namenode

COPY go.mod go.sum ./

RUN go mod download

COPY namenode/main.go ./

RUN go get github.com/Francisca-Gonzalez/Lab2_distribuidos

RUN go build -o namenode_bin .

ENTRYPOINT [ "/namenode/namenode_bin" ]